Introduce some tests in the pipeline before we kick of e2e
vmware-tap-on-public-cloud/quickstart-vmware-tanzu-application-platform pull request #57
Opened 2023-02-06 16:42 UTC by hoegaarden

This, for now, just runs some linting and other static checks.

In the future we will probably introduce more tests (e.g. inclusive-lang, shellcheck, unit tests, ...) which should probably run as additional `test-...` jobs in parallel to the `test-static` job, so that they can all run and be re-triggered in isolation.

2023-02-06 16:49 UTC, hoegaarden commented
Once https://github.com/vmware-tap-on-public-cloud/quickstart-vmware-tanzu-application-platform/pull/56 is merged I'd like to introduce shellcheck and inclusive-lang checks; probably not failing the pipeline initially, tho.

2023-02-06 18:33 UTC, satya-dillikar commented
I am not sure if we have already taken care of cfn-lint.

Look at the below commands, this repo helps to run all qs lint checks

```
git clone https://github.com/aws-quickstart/qs-cfn-lint-rules.git
cd qs-cfn-lint-rules
cfn-lint aws-tap-entrypoint-new-vpc.template.yaml -a ./qs_cfn_lint_rules/
```

I appreciate it if we can get this before the e2e-tests.

P.S.: Let me know if you want to merge the current changes as-is. I have no problem.

2023-02-06 18:34 UTC, satya-dillikar requested changes
confirm on cfn-lint. see my comments in conversation

2023-02-07 17:36 UTC, hoegaarden commented
> I am not sure if we have already taken care of cfn-lint.

I got bitten by things that `cfn-lint` (with out specific configuration) would have caught; that's why I made this PR while I was waiting for a stack to deploy.


> P.S.: Let me know if you want to merge the current changes as-is. I have no problem.

I am super happy to, and this was on the back of my head, to introduce more linting, I think I saw in the upstream repo that they have some more linting rules enabled and run some post-commit hooks. Maybe your snippet above is exactly / all they do there.

However, I'd still prefer to get this PR merged and whip up a story up "Make the same tests as in upstream run in our pipeline".

2023-02-07 18:31 UTC, aaronmeza approved these changes

2023-02-07 21:30 UTC, satya-dillikar approved these changes

2023-02-07 21:30 UTC, merged