tappc190 removing unecessary parameters
vmware-tap-on-public-cloud/quickstart-vmware-tanzu-application-platform pull request #74
Opened 2023-02-28 20:06 UTC by leclaist

[*tappc190*](https://jira.eng.vmware.com/browse/TAPPC-190)

* Removed parameter sample app name 
* Removed bastion os
* Removed bastion ssh port
* Added eks cluster name default value 
* Added qss3 bucket prefix default value 
* removed commented out content in post deploy doc

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-28 23:03 UTC, satya-dillikar requested changes
Please also add the actual CFT template files  code in this same PR.

2023-02-28 23:03 UTC, satya-dillikar commented on docs/deployment_guide/partner_editable/post_deployment.adoc
>  |`EKSClusterName`
EKSClusterName can be totally removed. Instead, we can have an auto-generated name in the code

2023-02-28 23:03 UTC, satya-dillikar commented on docs/deployment_guide/partner_editable/post_deployment.adoc
> -[%autowidth.stretch]
I am not sure if we want to remove OS and SSH config.

2023-03-02 17:09 UTC, leclaist commented on docs/deployment_guide/partner_editable/post_deployment.adoc
>  |`EKSClusterName`
removed

2023-03-02 19:45 UTC, satya-dillikar approved these changes

2023-03-02 22:47 UTC, merged

2023-03-02 22:47 UTC, satya-dillikar reviewed
updated branch