Test image relocation in the pipeline
vmware-tap-on-public-cloud/quickstart-vmware-tanzu-application-platform pull request #92
Opened 2023-03-14 21:13 UTC by hoegaarden

**Notes**:
- This is based on #90 ; I can rebase once #90 is merged
- changes to the structure of the pipeline will only materialize once merged into `main`

Changes:
- Add a separate taskcat test to test relocation of CE & TAP images.
- Run those tests in concourse as part of the "main" and the "PR" pipeline
- opportunistically does some pipeline cleanup (removal of `old_name` for already renamed jobs)

2023-03-14 21:27 UTC, hoegaarden commented
This adds the new test to the PR pipeline, which would prolong the PR pipeline for about 25min in the best case, much more in the worst case (in case we run into an error and need to wait for all wait conditions to time out).  
Do we maybe want to only run this test in the "main" pipeline, but not in the "PR" pipeline? What do you all think?

2023-03-15 16:12 UTC, leclaist approved these changes

2023-03-15 18:29 UTC, satya-dillikar requested changes

2023-03-15 18:29 UTC, satya-dillikar commented on .taskcat.yml
> +  relocation:
Add multi-cluster-ecr and single-cluster-ecr. Basically two new tests.

2023-03-15 18:30 UTC, satya-dillikar commented
Add these new tests for both the main and pr pipelines.

2023-03-16 11:40 UTC, hoegaarden commented
> Add these new tests for both the main and pr pipelines.

I wanted to not introduce too many tests, for "cost" reasons (actual $$$ cost, feedback time, and housekeeping time).
But happy to add those 2 test cases, esp. because its easy to be removed from our pipeline, but still have them run at release on AWS e2e check.

2023-03-17 00:24 UTC, satya-dillikar approved these changes

2023-03-17 00:25 UTC, merged